### ISSUE TITLE
resetFrenemies()  causes input delay on higher ping

### ISSUE THREAD

**Issue by Crazy24699** [Overwatch-1-Emulator/ow1-emulator#1594]
When on higher ping, such as 180+, there is a noticeable input delay when using abilies that move you on certain heros. Pharah Rocket jumping, pharah conc blast on herself, soldier helix blast and baptiest exo boots

**Comment by MaxwellJung** [comment]
I did notice this but couldn't exactly figure out why. I'll try to fix it for next release

**Comment by MaxwellJung** [comment]
update: I don't think this is related to `resetFrenemies()`
